# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartRecognize.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartRecognize(object):
    def setupUi(self, StartRecognize):
        StartRecognize.setObjectName("StartRecognize")
        StartRecognize.resize(600, 300)
        self.groupBox = QtWidgets.QGroupBox(StartRecognize)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 201, 241))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Get = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Get.setGeometry(QtCore.QRect(30, 30, 141, 41))
        self.pushButton_Get.setObjectName("pushButton_Get")
        self.pushButton_Recognize = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Recognize.setGeometry(QtCore.QRect(30, 100, 141, 41))
        self.pushButton_Recognize.setObjectName("pushButton_Recognize")
        self.pushButton_Tips = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Tips.setGeometry(QtCore.QRect(30, 170, 141, 41))
        self.pushButton_Tips.setObjectName("pushButton_Tips")
        self.groupBox_2 = QtWidgets.QGroupBox(StartRecognize)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 20, 291, 241))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_ImageResult = QtWidgets.QLabel(self.groupBox_2)
        self.label_ImageResult.setGeometry(QtCore.QRect(30, 30, 241, 131))
        self.label_ImageResult.setText("")
        self.label_ImageResult.setObjectName("label_ImageResult")
        self.label_RecognizeResult = QtWidgets.QLabel(self.groupBox_2)
        self.label_RecognizeResult.setGeometry(QtCore.QRect(30, 190, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        self.label_RecognizeResult.setFont(font)
        self.label_RecognizeResult.setText("")
        self.label_RecognizeResult.setObjectName("label_RecognizeResult")

        self.retranslateUi(StartRecognize)
        QtCore.QMetaObject.connectSlotsByName(StartRecognize)

    def retranslateUi(self, StartRecognize):
        _translate = QtCore.QCoreApplication.translate
        StartRecognize.setWindowTitle(_translate("StartRecognize", "手势识别系统"))
        self.groupBox.setTitle(_translate("StartRecognize", "操作按钮"))
        self.pushButton_Get.setText(_translate("StartRecognize", "获取手势"))
        self.pushButton_Recognize.setText(_translate("StartRecognize", "进行识别"))
        self.pushButton_Tips.setText(_translate("StartRecognize", "操作提示"))
        self.groupBox_2.setTitle(_translate("StartRecognize", "识别结果"))
